insert into paises(pais_id,nombre) values(1,"AFGANISTÁN");
insert into paises(pais_id,nombre) values(2,"ÅLAND");
insert into paises(pais_id,nombre) values(3,"ALBANIA");
insert into paises(pais_id,nombre) values(4,"ALEMANIA");
insert into paises(pais_id,nombre) values(5,"ANDORRA");
insert into paises(pais_id,nombre) values(6,"ANGOLA");
insert into paises(pais_id,nombre) values(7,"ANGUILA");
insert into paises(pais_id,nombre) values(8,"ANTIGUA Y BARBUDA");
insert into paises(pais_id,nombre) values(9,"ANTILLAS NEERLANDESAS");
insert into paises(pais_id,nombre) values(10,"ARABIA SAUDITA");
insert into paises(pais_id,nombre) values(11,"ARGELIA");
insert into paises(pais_id,nombre) values(12,"ARGENTINA");
insert into paises(pais_id,nombre) values(13,"ARMENIA");
insert into paises(pais_id,nombre) values(14,"ARUBA");
insert into paises(pais_id,nombre) values(15,"AUSTRALIA");
insert into paises(pais_id,nombre) values(16,"AUSTRIA");
insert into paises(pais_id,nombre) values(17,"AZERBAIYÁN");
insert into paises(pais_id,nombre) values(18,"BAHAMAS");
insert into paises(pais_id,nombre) values(19,"BARÉIN");
insert into paises(pais_id,nombre) values(20,"BANGLADÉS");
insert into paises(pais_id,nombre) values(21,"BARBADOS");
insert into paises(pais_id,nombre) values(22,"BÉLGICA");
insert into paises(pais_id,nombre) values(23,"BELICE");
insert into paises(pais_id,nombre) values(24,"BENÍN");
insert into paises(pais_id,nombre) values(25,"BERMUDAS");
insert into paises(pais_id,nombre) values(26,"BIELORRUSIA");
insert into paises(pais_id,nombre) values(27,"BIRMANIA");
insert into paises(pais_id,nombre) values(28,"BOLIVIA");
insert into paises(pais_id,nombre) values(29,"BOSNIA Y HERZEGOVINA");
insert into paises(pais_id,nombre) values(30,"BOTSUANA");
insert into paises(pais_id,nombre) values(31,"ISLA BOUVET");
insert into paises(pais_id,nombre) values(32,"BRASIL");
insert into paises(pais_id,nombre) values(33,"BRUNÉI");
insert into paises(pais_id,nombre) values(34,"BULGARIA");
insert into paises(pais_id,nombre) values(35,"BURKINA FASO");
insert into paises(pais_id,nombre) values(36,"BURUNDI");
insert into paises(pais_id,nombre) values(37,"BUTÁN");
insert into paises(pais_id,nombre) values(38,"CABO VERDE");
insert into paises(pais_id,nombre) values(39,"ISLAS CAIMÁN");
insert into paises(pais_id,nombre) values(40,"CAMBOYA");
insert into paises(pais_id,nombre) values(41,"CAMERÚN");
insert into paises(pais_id,nombre) values(42,"CANADÁ");
insert into paises(pais_id,nombre) values(43,"REPÚBLICA CENTROAFRICANA");
insert into paises(pais_id,nombre) values(44,"CHAD");
insert into paises(pais_id,nombre) values(45,"REPÚBLICA CHECA");
insert into paises(pais_id,nombre) values(46,"CHILE");
insert into paises(pais_id,nombre) values(47,"CHINA");
insert into paises(pais_id,nombre) values(48,"CHIPRE");
insert into paises(pais_id,nombre) values(49,"ISLAS COCOS");
insert into paises(pais_id,nombre) values(50,"COLOMBIA");
insert into paises(pais_id,nombre) values(51,"COMORAS");
insert into paises(pais_id,nombre) values(52,"REPÚBLICA DEL CONGO");
insert into paises(pais_id,nombre) values(53,"REP. DEM. DEL CONGO");
insert into paises(pais_id,nombre) values(54,"ISLAS COOK");
insert into paises(pais_id,nombre) values(55,"COREA DEL NORTE");
insert into paises(pais_id,nombre) values(56,"COREA DEL SUR");
insert into paises(pais_id,nombre) values(57,"COSTA DE MARFIL");
insert into paises(pais_id,nombre) values(58,"COSTA RICA");
insert into paises(pais_id,nombre) values(59,"CROACIA");
insert into paises(pais_id,nombre) values(60,"CUBA");
insert into paises(pais_id,nombre) values(61,"DINAMARCA");
insert into paises(pais_id,nombre) values(62,"DOMINICA");
insert into paises(pais_id,nombre) values(63,"REPÚBLICA DOMINICANA");
insert into paises(pais_id,nombre) values(64,"ECUADOR");
insert into paises(pais_id,nombre) values(65,"EGIPTO");
insert into paises(pais_id,nombre) values(66,"EL SALVADOR");
insert into paises(pais_id,nombre) values(67,"EMIRATOS ÁRABES UNIDOS");
insert into paises(pais_id,nombre) values(68,"ERITREA");
insert into paises(pais_id,nombre) values(69,"ESLOVAQUIA");
insert into paises(pais_id,nombre) values(70,"ESLOVENIA");
insert into paises(pais_id,nombre) values(71,"ESPAÑA");
insert into paises(pais_id,nombre) values(72,"ESTADOS UNIDOS");
insert into paises(pais_id,nombre) values(73,"ESTONIA");
insert into paises(pais_id,nombre) values(74,"ETIOPÍA");
insert into paises(pais_id,nombre) values(75,"ISLAS FEROE");
insert into paises(pais_id,nombre) values(76,"FILIPINAS");
insert into paises(pais_id,nombre) values(77,"FINLANDIA");
insert into paises(pais_id,nombre) values(78,"FIYI");
insert into paises(pais_id,nombre) values(79,"FRANCIA");
insert into paises(pais_id,nombre) values(80,"GABÓN");
insert into paises(pais_id,nombre) values(81,"GAMBIA");
insert into paises(pais_id,nombre) values(82,"GEORGIA");
insert into paises(pais_id,nombre) values(83,"ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR");
insert into paises(pais_id,nombre) values(84,"GHANA");
insert into paises(pais_id,nombre) values(85,"GIBRALTAR");
insert into paises(pais_id,nombre) values(86,"GRANADA");
insert into paises(pais_id,nombre) values(87,"GRECIA");
insert into paises(pais_id,nombre) values(88,"GROENLANDIA");
insert into paises(pais_id,nombre) values(89,"GUADALUPE");
insert into paises(pais_id,nombre) values(90,"GUAM");
insert into paises(pais_id,nombre) values(91,"GUATEMALA");
insert into paises(pais_id,nombre) values(92,"GUAYANA FRANCESA");
insert into paises(pais_id,nombre) values(93,"GUERNSEY");
insert into paises(pais_id,nombre) values(94,"GUINEA");
insert into paises(pais_id,nombre) values(95,"GUINEA ECUATORIAL");
insert into paises(pais_id,nombre) values(96,"GUINEA-BISSAU");
insert into paises(pais_id,nombre) values(97,"GUYANA");
insert into paises(pais_id,nombre) values(98,"HAITÍ");
insert into paises(pais_id,nombre) values(99,"ISLAS HEARD Y MCDONALD");
insert into paises(pais_id,nombre) values(100,"HONDURAS");
insert into paises(pais_id,nombre) values(101,"HONG KONG");
insert into paises(pais_id,nombre) values(102,"HUNGRÍA");
insert into paises(pais_id,nombre) values(103,"INDIA");
insert into paises(pais_id,nombre) values(104,"INDONESIA");
insert into paises(pais_id,nombre) values(105,"IRÁN");
insert into paises(pais_id,nombre) values(106,"IRAK");
insert into paises(pais_id,nombre) values(107,"IRLANDA");
insert into paises(pais_id,nombre) values(108,"ISLANDIA");
insert into paises(pais_id,nombre) values(109,"ISRAEL");
insert into paises(pais_id,nombre) values(110,"ITALIA");
insert into paises(pais_id,nombre) values(111,"JAMAICA");
insert into paises(pais_id,nombre) values(112,"JAPÓN");
insert into paises(pais_id,nombre) values(113,"JERSEY");
insert into paises(pais_id,nombre) values(114,"JORDANIA");
insert into paises(pais_id,nombre) values(115,"KAZAJISTÁN");
insert into paises(pais_id,nombre) values(116,"KENIA");
insert into paises(pais_id,nombre) values(117,"KIRGUISTÁN");
insert into paises(pais_id,nombre) values(118,"KIRIBATI");
insert into paises(pais_id,nombre) values(119,"KUWAIT");
insert into paises(pais_id,nombre) values(120,"LAOS");
insert into paises(pais_id,nombre) values(121,"LESOTO");
insert into paises(pais_id,nombre) values(122,"LETONIA");
insert into paises(pais_id,nombre) values(123,"LÍBANO");
insert into paises(pais_id,nombre) values(124,"LIBERIA");
insert into paises(pais_id,nombre) values(125,"LIBIA");
insert into paises(pais_id,nombre) values(126,"LIECHTENSTEIN");
insert into paises(pais_id,nombre) values(127,"LITUANIA");
insert into paises(pais_id,nombre) values(128,"LUXEMBURGO");
insert into paises(pais_id,nombre) values(129,"MACAO");
insert into paises(pais_id,nombre) values(130,"REPÚBLICA DE MACEDONIA");
insert into paises(pais_id,nombre) values(131,"MADAGASCAR");
insert into paises(pais_id,nombre) values(132,"MALASIA");
insert into paises(pais_id,nombre) values(133,"MALAUI");
insert into paises(pais_id,nombre) values(134,"MALDIVAS");
insert into paises(pais_id,nombre) values(135,"MALÍ");
insert into paises(pais_id,nombre) values(136,"MALTA");
insert into paises(pais_id,nombre) values(137,"ISLAS MALVINAS");
insert into paises(pais_id,nombre) values(138,"ISLA DE MAN");
insert into paises(pais_id,nombre) values(139,"ISLAS MARIANAS DEL NORTE");
insert into paises(pais_id,nombre) values(140,"MARRUECOS");
insert into paises(pais_id,nombre) values(141,"ISLAS MARSHALL");
insert into paises(pais_id,nombre) values(142,"MARTINICA");
insert into paises(pais_id,nombre) values(143,"MAURICIO");
insert into paises(pais_id,nombre) values(144,"MAURITANIA");
insert into paises(pais_id,nombre) values(145,"MAYOTTE");
insert into paises(pais_id,nombre) values(146,"MÉXICO");
insert into paises(pais_id,nombre) values(147,"MICRONESIA");
insert into paises(pais_id,nombre) values(148,"MOLDAVIA");
insert into paises(pais_id,nombre) values(149,"MÓNACO");
insert into paises(pais_id,nombre) values(150,"MONGOLIA");
insert into paises(pais_id,nombre) values(151,"MONTENEGRO");
insert into paises(pais_id,nombre) values(152,"MONTSERRAT");
insert into paises(pais_id,nombre) values(153,"MOZAMBIQUE");
insert into paises(pais_id,nombre) values(154,"NAMIBIA");
insert into paises(pais_id,nombre) values(155,"NAURU");
insert into paises(pais_id,nombre) values(156,"ISLA DE NAVIDAD");
insert into paises(pais_id,nombre) values(157,"NEPAL");
insert into paises(pais_id,nombre) values(158,"NICARAGUA");
insert into paises(pais_id,nombre) values(159,"NÍGER");
insert into paises(pais_id,nombre) values(160,"NIGERIA");
insert into paises(pais_id,nombre) values(161,"NIUE");
insert into paises(pais_id,nombre) values(162,"NORFOLK");
insert into paises(pais_id,nombre) values(163,"NORUEGA");
insert into paises(pais_id,nombre) values(164,"NUEVA CALEDONIA");
insert into paises(pais_id,nombre) values(165,"NUEVA ZELANDA");
insert into paises(pais_id,nombre) values(166,"OMÁN");
insert into paises(pais_id,nombre) values(167,"PAÍSES BAJOS");
insert into paises(pais_id,nombre) values(168,"PAKISTÁN");
insert into paises(pais_id,nombre) values(169,"PALAOS");
insert into paises(pais_id,nombre) values(170,"AUTORIDAD NACIONAL PALESTINA");
insert into paises(pais_id,nombre) values(171,"PANAMÁ");
insert into paises(pais_id,nombre) values(172,"PAPÚA NUEVA GUINEA");
insert into paises(pais_id,nombre) values(173,"PARAGUAY");
insert into paises(pais_id,nombre) values(174,"PERÚ");
insert into paises(pais_id,nombre) values(175,"ISLAS PITCAIRN");
insert into paises(pais_id,nombre) values(176,"POLINESIA FRANCESA");
insert into paises(pais_id,nombre) values(177,"POLONIA");
insert into paises(pais_id,nombre) values(178,"PORTUGAL");
insert into paises(pais_id,nombre) values(179,"PUERTO RICO");
insert into paises(pais_id,nombre) values(180,"CATAR");
insert into paises(pais_id,nombre) values(181,"REINO UNIDO");
insert into paises(pais_id,nombre) values(182,"REUNIÓN");
insert into paises(pais_id,nombre) values(183,"RUANDA");
insert into paises(pais_id,nombre) values(184,"RUMANÍA");
insert into paises(pais_id,nombre) values(185,"RUSIA");
insert into paises(pais_id,nombre) values(186,"REPÚBLICA ÁRABE SAHARAUI DEMOCRÁTICA");
insert into paises(pais_id,nombre) values(187,"ISLAS SALOMÓN");
insert into paises(pais_id,nombre) values(188,"SAMOA");
insert into paises(pais_id,nombre) values(189,"SAMOA ESTADOUNIDENSE");
insert into paises(pais_id,nombre) values(190,"SAN BARTOLOMÉ");
insert into paises(pais_id,nombre) values(191,"SAN CRISTÓBAL Y NIEVES");
insert into paises(pais_id,nombre) values(192,"SAN MARINO");
insert into paises(pais_id,nombre) values(193,"SAN MARTÍN");
insert into paises(pais_id,nombre) values(194,"SAN PEDRO Y MIQUELÓN");
insert into paises(pais_id,nombre) values(195,"SAN VICENTE Y LAS GRANADINAS");
insert into paises(pais_id,nombre) values(196,"SANTA HELENA, A. Y T.");
insert into paises(pais_id,nombre) values(197,"SANTA LUCÍA");
insert into paises(pais_id,nombre) values(198,"SANTO TOMÉ Y PRÍNCIPE");
insert into paises(pais_id,nombre) values(199,"SENEGAL");
insert into paises(pais_id,nombre) values(200,"SERBIA");
insert into paises(pais_id,nombre) values(201,"SEYCHELLES");
insert into paises(pais_id,nombre) values(202,"SIERRA LEONA)";
insert into paises(pais_id,nombre) values(203,"SINGAPUR");
insert into paises(pais_id,nombre) values(204,"SIRIA");
insert into paises(pais_id,nombre) values(205,"SOMALIA");
insert into paises(pais_id,nombre) values(206,"SRI LANKA");
insert into paises(pais_id,nombre) values(207,"SUAZILANDIA");
insert into paises(pais_id,nombre) values(208,"SUDÁFRICA");
insert into paises(pais_id,nombre) values(209,"SUDÁN");
insert into paises(pais_id,nombre) values(210,"SUECIA");
insert into paises(pais_id,nombre) values(211,"SUIZA");
insert into paises(pais_id,nombre) values(212,"SURINAM");
insert into paises(pais_id,nombre) values(213,"SVALBARD Y JAN MAYEN");
insert into paises(pais_id,nombre) values(214,"TAILANDIA");
insert into paises(pais_id,nombre) values(215,"TAIWÁN");
insert into paises(pais_id,nombre) values(216,"TANZANIA");
insert into paises(pais_id,nombre) values(217,"TAYIKISTÁN");
insert into paises(pais_id,nombre) values(218,"TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO");
insert into paises(pais_id,nombre) values(219,"TERRITORIOS AUSTRALES FRANCESES");
insert into paises(pais_id,nombre) values(220,"TIMOR ORIENTAL");
insert into paises(pais_id,nombre) values(221,"TOGO");
insert into paises(pais_id,nombre) values(222,"TOKELAU");
insert into paises(pais_id,nombre) values(223,"TONGA");
insert into paises(pais_id,nombre) values(224,"TRINIDAD Y TOBAGO");
insert into paises(pais_id,nombre) values(225,"TÚNEZ");
insert into paises(pais_id,nombre) values(226,"ISLAS TURCAS Y CAICOS");
insert into paises(pais_id,nombre) values(227,"TURKMENISTÁN");
insert into paises(pais_id,nombre) values(228,"TURQUÍA");
insert into paises(pais_id,nombre) values(229,"TUVALU");
insert into paises(pais_id,nombre) values(230,"UCRANIA");
insert into paises(pais_id,nombre) values(231,"UGANDA");
insert into paises(pais_id,nombre) values(232,"URUGUAY");
insert into paises(pais_id,nombre) values(233,"UZBEKISTÁN");
insert into paises(pais_id,nombre) values(234,"VANUATU");
insert into paises(pais_id,nombre) values(235,"CIUDAD DEL VATICANO");
insert into paises(pais_id,nombre) values(236,"VENEZUELA");
insert into paises(pais_id,nombre) values(237,"VIETNAM");
insert into paises(pais_id,nombre) values(238,"ISLAS VÍRGENES BRITÁNICAS");
insert into paises(pais_id,nombre) values(239,"ISLAS VÍRGENES DE LOS ESTADOS UNIDOS");
insert into paises(pais_id,nombre) values(240,"WALLIS Y FUTUNA");
insert into paises(pais_id,nombre) values(241,"YEMEN");
insert into paises(pais_id,nombre) values(242,"YIBUTI");
insert into paises(pais_id,nombre) values(243,"ZAMBIA");
insert into paises(pais_id,nombre) values(244,"ZIMBABUE");